services:
  iris_db:
    build: .
    container_name: iris_db
    hostname: iris_db
    ports:
      - "10501:1972"
    init: true
    volumes:
      - /Users/tokuyama/workspace/iris-2025.1-ecp/iris_db/opt/iris:/opt/iris
    tty: true
    environment:
      - TZ=JST-9

  webgw_db:
    image: containers.intersystems.com/intersystems/webgateway-arm64:2025.1
    container_name: webgw_db
    hostname: webgw_db
    init: true
    volumes:
      - /Users/tokuyama/workspace/iris-2025.1-ecp/webgw_db/opt/iris:/opt/iris
    ports:
      - 10502:80
      - 10503:443
    environment:
    - ISC_CSP_CONF_FILE=/opt/iris/CSP.conf
    - ISC_CSP_INI_FILE=/opt/iris/CSP.ini
    tty: true

  iris_ap:
    build: .
    container_name: iris_ap
    hostname: iris_ap
    ports:
      - "10504:1972"
    init: true
    volumes:
      - /Users/tokuyama/workspace/iris-2025.1-ecp/iris_ap/opt/iris:/opt/iris
    tty: true
    environment:
      - TZ=JST-9

  webgw_ap:
    image: containers.intersystems.com/intersystems/webgateway-arm64:2025.1
    container_name: webgw_ap
    hostname: webgw_ap
    init: true
    volumes:
      - /Users/tokuyama/workspace/iris-2025.1-ecp/webgw_ap/opt/iris:/opt/iris
    ports:
      - 10505:80
      - 10506:443
    environment:
    - ISC_CSP_CONF_FILE=/opt/iris/CSP.conf
    - ISC_CSP_INI_FILE=/opt/iris/CSP.ini
    tty: true